config/routes.rb
Rails.application.routes.draw do

resources :projects do 
  resources :time_entries
end


end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :time_entries
	validates :name, presence: true, uniqueness: true, format: {with: /[\w]/}

def self.clean_old
	old_projects = Project.where("created_at < ?", 1.week.ago)
	old_projects.destroy_all
end

end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
	belongs_to :project
	validates :date, presence: true
	validates :hours, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
	validates :minutes, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.order(created_at: :desc).limit(10)
		render 'index'
	end

	def show
		@my_project = Project.find(params[:id])
		render 'show'
	end

	def new
		@my_project = Project.new
		render 'new'
	end

	def create
		@my_project = Project.new(:name => params[:project][:name], :description => params[:project][:description])
		@my_project.save

		redirect_to "/projects/#{@my_project.id}"
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
		render 'home' #name of view template
	end

	def contact
		render 'contact'
	end

	def say_name
		@name = params[:name]
		render 'say_name'
	end

	def calculator
		render 'calculator'
	end

	def calculate
		@num1 = params[:first_num].to_f
		@num2 = params[:second_num].to_f
		@result = @num1 + @num2
		render 'calculate'
	end

end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def index
		@my_project = Project.find(params[:project_id])
		@my_entries = @my_project.time_entries
		render 'index'
	end

	def new
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.new
		render 'new'
	end

	def create
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.new(entry_params)
		if @my_entry.save
			redirect_to action: 'index', controller: 'time_entries', project_id:
		@my_project.id
		else
			render 'new'
		end
	end

	def edit
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.find(params[:id])
	end

	def update
		@my_project = Project.find_by(id: params[:project_id])
		@my_entry = @my_project.time_entries.find_by(id: params[:id])
		if @my_entry.update(entry_params)
			redirect_to action: 'index', controller: 'time_entries', project_id: @my_project.id
		else
			render 'edit'
		end

	end

	private

	def entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date, :comment)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<h1>My projects</h1>
<ul>
	<% @projects.each do |project| %>
		<% if project.description != nil %>
			<li><%= project.name + " - " + project.description%></li>
		<% else %>
			<li><%= project.name %>
		<% end %>
	<% end %>
</ul>

app/views/projects/new.html.erb
<h1>Add a project</h1>
<%= form_for @my_project do |f| %>
	<div>
		<%= f.label :name %>
	</div>
	<div>
		<%= f.text_field :name, placeholder: "Your project name" %>
	</div>
	<div>
		<%= f.label :description %>
	</div>
	<div>
		<%= f.text_area :description, placeholder: "Your project description", cols: "30", rows: "10" %>
	</div>
	<div>
		<%= f.button %>
	</div>
<% end %>

app/views/projects/show.html.erb
<h1>My project</h1>
<p><strong>Name: </strong> <%= @my_project.name %></p>
<p><strong>Description: </strong> <%= @my_project.description %></p>

app/views/site/calculate.html.erb
<h1>The result of <%= @num1 %> + <%= @num2 %> is <%= @result %> </h1>

app/views/site/calculator.html.erb
<form action="/calculate" method="POST">
	<input type="text" name="first_num" placeholder="First Number">
	<input type="text" name="second_num" placeholder="Second Number">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<button type="submit">Add</button>
</form>

app/views/site/contact.html.erb
<h1>Contact page</h1>
<p>E-mail address: contact@timetracking.com</p>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>
<p>Ironhack powered</p>

app/views/site/say_name.html.erb
<h1>And your name is:</h1>
<h3><%= @name.upcase %></h3>

<%= image_tag "/assets/carol.gif", alt: "Gif of Carol from the Walking Dead smiling"%>

app/views/time_entries/_form.html.erb
<% if @my_entry.errors.any? %>
	<ul>
		<% @my_entry.errors.full_messages.each do |error_msg| %>
			<li> <%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@my_project, @my_entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>

	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>

	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>

	<%= f.label :comment %>
	<%= f.text_area :comment %>
	<br>
	
	<%= f.submit "Save" %>
	<%= link_to 'Cancel', project_time_entries_path(@my_project) %>
<% end %>

app/views/time_entries/edit.html.erb
<h2>Edit time entry for <%= @my_project.name %> </h2>

<%= render "form" %>

app/views/time_entries/index.html.erb
<h1><%= @my_project.name %></h1>
<ul>
	<% @my_entries.each do |entry| %>
		<li>
			<%= entry.hours %> h
			<%= entry.minutes %> m -
			<%= entry.date %> 
			<%= entry.comment %>
			<%= link_to "Edit Entry", "/projects/#{@my_project.id}/time_entries/#{entry.id}/edit" %>
		</li>
	<% end %>

</ul>

app/views/time_entries/new.html.erb
<h2>Creating a new time entry in <%= @my_project.name %> project</h2>

<%= render "form" %>